(ns real-corpus
  "A real corpus, read off this workspace's own disk.

  Every number this subsystem has produced so far came from `synth/corpus`: a
  Zipf draw over a vocabulary of `w<rank>` tokens. That is the right shape for
  isolating a cost model — the distribution is known and the corpus is
  reproducible from a seed — but it leaves two things unmeasured, and one of
  them is not a matter of degree:

  1. **The CJK path never runs.** `analyze/tokenize` splits ASCII runs AND
     emits CJK bigrams, and the deployed `web.search` this format matches is
     mostly Japanese. `w1234` is ASCII. So the analyzer branch that the target
     corpus would actually take had never been benchmarked at all.
  2. **A synthetic tail is short.** Real text has far more rare terms, which
     makes the dictionary deeper (logarithmic, so cheap) and mid-frequency
     terms far more selective (which should make queries cheaper). Both effects
     were argued in ADR-2608071500's caveats and neither was measured.

  What is here: the workspace's own ADRs (`90-docs/adr/*.edn`, ~2,000 documents
  of mixed Japanese and English technical prose) and the READMEs of every
  checked-out repository (~3,700). Real text, written by many hands, naturally
  clustered — ADRs by topic and READMEs by organisation — which is the corpus
  shape the clustered synthetic was invented to imitate.

  It is not a web crawl. It is small (thousands, not millions), it is
  technical, and it over-represents this workspace's own vocabulary. What it
  is NOT is generated by the same assumptions the index was designed under,
  which is the specific failure mode a synthetic benchmark cannot detect."
  (:require [clojure.string :as str]))

(def fs (js/require "node:fs"))
(def path (js/require "node:path"))

(defn- read-safe [p]
  (try (.readFileSync fs p "utf8") (catch :default _ nil)))

(defn- strip-edn
  "ADRs are EDN tx-data whose prose lives in string values. Reading them as
  EDN and pulling `:adr/body` would be cleaner, but a fifth of them do not
  parse (the workspace's own `docs-edn-only verify` reports 7 known-broken and
  more that are merely large), and a corpus that silently dropped the
  unparseable ones would be a biased sample of the corpus. Strip the syntax
  instead and keep every document."
  [s]
  (-> s
      (str/replace #"[\[\]{}()]" " ")
      (str/replace #":[a-zA-Z][a-zA-Z0-9/_-]*" " ")
      (str/replace #"\\n" " ")
      (str/replace #"\"" " ")))

(defn- files-in [dir pred]
  (try
    (->> (.readdirSync fs dir)
         (map #(.join path dir %))
         (filter pred)
         vec)
    (catch :default _ [])))

(defn adr-docs
  "ADRs, in filename order — which is chronological, since the ids are
  timestamps. That ordering is what makes a shard a time slice."
  [root limit]
  (let [dir (.join path root "90-docs" "adr")]
    (->> (files-in dir #(str/ends-with? % ".edn"))
         sort
         (take limit)
         (keep (fn [p]
                 (when-let [s (read-safe p)]
                   (when (> (count s) 200)
                     {:url (str "adr:" (.basename path p))
                      :title (str/replace (.basename path p ".edn") #"-" " ")
                      :text (subs (strip-edn s) 0 20000)}))))
         vec)))

(defn readme-docs
  "One README per checked-out repository, grouped by organisation.

  Grouping is the point: `build!` assigns doc-ids by position, so documents
  emitted org by org land in the same shard. This is the real version of what
  `synth/clustered-corpus` models, and the first chance to see whether real
  topical clustering separates shards as cleanly as the synthetic one did."
  [root limit]
  (let [orgs-dir (.join path root "orgs")
        orgs (sort (try (vec (.readdirSync fs orgs-dir)) (catch :default _ [])))]
    (->> (for [org orgs
               :let [od (.join path orgs-dir org)]
               repo (sort (try (vec (.readdirSync fs od)) (catch :default _ [])))
               :let [p (.join path od repo "README.md")]
               :when (.existsSync fs p)]
           (when-let [s (read-safe p)]
             (when (> (count s) 200)
               {:url (str "repo:" org "/" repo)
                :title (str org " " (str/replace repo #"-" " "))
                :text (subs s 0 20000)
                :org org})))
         (keep identity)
         (take limit)
         vec)))

(defn corpus
  "`:adr` / `:readme` / `:both`. `:both` puts ADRs first so the two halves are
  contiguous rather than interleaved."
  ([root kind] (corpus root kind 100000))
  ([root kind limit]
   (case kind
     :adr (adr-docs root limit)
     :readme (readme-docs root limit)
     :both (vec (concat (adr-docs root limit) (readme-docs root limit))))))

(defn queries
  "Queries drawn from the corpus itself, spanning the frequency range.

  Taken from real term frequencies rather than written by hand: a hand-picked
  query set is a description of what the author expected the index to be good
  at. Includes CJK terms explicitly — the whole reason for a real corpus here
  is that the bigram path had never run."
  [docs analyze-fn]
  (let [df (reduce (fn [acc d]
                     (reduce (fn [a t] (update a t (fnil inc 0)))
                             acc (distinct (analyze-fn (str (:title d) " " (:text d))))))
                   {} docs)
        n (count docs)
        ranked (->> df (sort-by (comp - second)) vec)
        cjk? (fn [t] (re-find #"[぀-ヿ一-鿿]" t))
        at (fn [frac] (first (nth ranked (min (dec (count ranked))
                                              (int (* frac (count ranked)))) [nil nil])))
        cjk-at (fn [frac]
                 (let [cs (filterv (comp cjk? first) ranked)]
                   (when (seq cs)
                     (first (nth cs (min (dec (count cs)) (int (* frac (count cs)))))))))]
    {:doc-count n
     :vocabulary (count ranked)
     :queries (vec (keep identity
                         [(at 0.001)                       ; very common
                          (at 0.02)                        ; common
                          (at 0.20)                        ; mid
                          (cjk-at 0.01)                    ; common CJK bigram
                          (cjk-at 0.20)                    ; mid CJK bigram
                          (when-let [a (at 0.02)] (when-let [b (at 0.20)] (str a " " b)))
                          (when-let [a (cjk-at 0.01)]
                            (when-let [b (cjk-at 0.20)] (str a " " b)))]))}))
